# Generated by Django 4.1.11 on 2023-11-30 21:06

from django.conf import settings
from django.db import migrations, models
import spotify_controller.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('session_id', models.CharField(default=spotify_controller.models.generate_random_id, max_length=10, unique=True)),
                ('host', models.CharField(max_length=50)),
                ('current_song', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
