# Generated by Django 4.1.11 on 2023-11-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionroom',
            name='temp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
