# Generated by Django 4.1.11 on 2023-12-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_controller', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
