# Generated by Django 4.1.11 on 2023-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_controller', '0004_rename_user_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionroom',
            name='users',
        ),
        migrations.AddField(
            model_name='sessionroom',
            name='users',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
