# Generated by Django 4.1.11 on 2023-12-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_controller', '0007_alter_sessionroom_host_alter_sessionroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default=65432, max_length=50),
            preserve_default=False,
        ),
    ]
